initial_date: 01/01/2020 00:00:00
test:
  column_names:
    - fecha
    - acumuladas
    - amazonas
    - antioquia
    - arauca
    - atlantico
    - bogota
    - bolivar
    - boyaca
    - caldas
    - caqueta
    - casanare
    - cauca
    - cesar
    - choco
    - cordoba
    - cundinamarca
    - guainia
    - guajira
    - guaviare
    - huila
    - magdalena
    - meta
    - narino
    - norte_de_santander
    - putumayo
    - quindio
    - risaralda
    - san_andres
    - santander
    - sucre
    - tolima
    - valle_del_cauca
    - vaupes
    - vichada
    - procedencia_desconocida
    - barranquila
    - cartagena
    - santa_marta
    - positivas_acumuladas
    - negativas_acumuladas
    - positividad_acumulada
    - indeterminadas
  url: https://www.datos.gov.co/resource/8835-5baf.csv
daily_cases:
  column_names:
    - id_de_caso
    - fecha_de_notificaci_n
    - departamento
    - departamento_nom
    - ciudad_municipio
    - ciudad_municipio_nom
    - edad
    - unidad_medida
    - sexo
    - fuente_tipo_contagio
    - ubicacion
    - estado
    - pais_viajo_1_cod
    - pais_viajo_1_nom
    - recuperado
    - fecha_inicio_sintomas
    - fecha_muerte
    - fecha_diagnostico
    - fecha_recuperado
    - tipo_recuperacion
    - per_etn_
    - nom_grupo_
  url: https://www.datos.gov.co/resource/gt2j-8ykr.csv
  filters:
    date: '?fecha_reporte_web=DATE&$limit=50000&$$app_token=WciL9p4Q0bKxilgau1iCHEZIS'