search_tweets_v2:
  endpoint: https://api.twitter.com/2/tweets/search/recent
  consumer_key: <<CONSUMER_KEY>>
  consumer_secret: <<CONSUMER_SECRET>>
  bearer_token: <<BEARER_TOKEN>>
query: 'covid19 colombia lang:es'